---
deployment:
  tasks:
    - export HOME=/home/kelleyryscreencr
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction --working-dir=$PWD
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    # adjust permissions if needed
    - chown -R USERNAME:USERNAME storage bootstrap/cache
    - chmod -R 775 storage bootstrap/cache
